# Please enter the following information

first_Name = input('First name')
last_Name = input('Last name')
email_address = input('Email address')
phone_Number = input('Phone')
job_Title = input('Job title')
id_Number = input('ID number')
hair_colour = input('Hair colour')
eye_colour = input('Eye colour')
month = input('Starting month')
training = input('Completed additional training')

print("\n The ID card is:")
print("___________________________")
print(f"{last_Name.upper()}, {first_Name.capitalize()}")
print(job_Title.title())
print(f"ID: {id_Number}")
print()
print(email_address.lower())
print(phone_Number)
print()
print(f"Hair: {hair_colour:15} Eyes: {eye_colour}")
print(f"Month: {month:14} Traning: {training}")
print("____________________________")
